/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTextField;
/**
 *
 * @author pinzo
 */
public class GestionTareas extends javax.swing.JPanel {
    /**
     * Creates new form GestionTareas
     */
   public GestionTareas() {
        initComponents();
    }

    // =======================================================
    // MÉTODOS GETTER (Puentes para el Controlador)
    // Estos métodos permiten al Controlador leer o modificar la pantalla.
    // =======================================================

    // Permite leer lo que el usuario escribió en el campo "Título"
    public JTextField getTxtRecordatorio() {
        return CampoRecordatorio1;
    }

    // Permite leer lo que el usuario escribió en el campo "Descripción"
    public JTextField getTxtDescripcion() {
        return DescripcionTarea; 
    }

    // Permite leer lo que el usuario escribió en el campo "Fecha"
    public JTextField getTxtFecha() {
        return CampoFecha; 
    }
    
    // Permite saber qué categoría seleccionó el usuario (General, Hoy, Importante)
    public JComboBox<String> getCmbCategoria() {
        return CategoriaTarea;
    }

    // Permite al controlador acceder a la lista visual para agregar o quitar tareas
    public JList<String> getJList() {
        return jList1;
    }
    
    // =======================================================
    // GETTERS DE BOTONES (Para que el Controlador escuche los clics)
    // =======================================================

    public JButton getBtnCrear() {
        return BtnCrearTarea; 
    }
    
    public JButton getBtnTareaCompleta() {
        return BtnTareaCompleta;
    }
    
    public JButton getBtnEliminar() {
        return BtnEliminar; 
    }

    // =======================================================
    // FUNCIONES VISUALES
    // =======================================================

    // Borra todo el texto de los campos y reinicia el menú desplegable
    // Se llama después de guardar una tarea exitosamente.
    public void limpiarCampos() {
        CampoRecordatorio1.setText(""); // Borra título
        DescripcionTarea.setText("");   // Borra descripción
        CampoFecha.setText("");         // Borra fecha
        CategoriaTarea.setSelectedIndex(0); // Vuelve a seleccionar la primera opción
        CampoRecordatorio1.requestFocus();  // Pone el cursor listo para escribir de nuevo
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CampoRecordatorio1 = new javax.swing.JTextField();
        BtnCrearTarea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        BtnTareaCompleta = new javax.swing.JButton();
        DescripcionTarea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CategoriaTarea = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        BtnEliminar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Crea tu recordatorio ");

        CampoRecordatorio1.setBackground(new java.awt.Color(242, 242, 242));
        CampoRecordatorio1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        CampoRecordatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoRecordatorio1ActionPerformed(evt);
            }
        });

        BtnCrearTarea.setText("Crear");
        BtnCrearTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearTareaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        BtnTareaCompleta.setText("Completada");

        DescripcionTarea.setBackground(new java.awt.Color(242, 242, 242));
        DescripcionTarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        DescripcionTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionTareaActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción (Opcional)");

        CampoFecha.setBackground(new java.awt.Color(242, 242, 242));
        CampoFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        CampoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFechaActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha (Opcional)");

        jLabel4.setText("Tus Tareas pendientes");

        CategoriaTarea.setBackground(new java.awt.Color(242, 242, 242));
        CategoriaTarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Tarea de hoy", "Importantes" }));
        CategoriaTarea.setBorder(null);
        CategoriaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaTareaActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoria");

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(CampoRecordatorio1)
                                .addComponent(DescripcionTarea)
                                .addComponent(jLabel2)
                                .addComponent(CampoFecha)
                                .addComponent(jLabel3)
                                .addComponent(CategoriaTarea, 0, 229, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnTareaCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(BtnCrearTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(157, 157, 157))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(BtnTareaCompleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoRecordatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(CategoriaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescripcionTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(BtnCrearTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CampoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFechaActionPerformed

    private void DescripcionTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionTareaActionPerformed

    private void BtnCrearTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCrearTareaActionPerformed

    private void CampoRecordatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoRecordatorio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoRecordatorio1ActionPerformed

    private void CategoriaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaTareaActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarActionPerformed
// 1. Getter para la descripción
    

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearTarea;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnTareaCompleta;
    private javax.swing.JTextField CampoFecha;
    private javax.swing.JTextField CampoRecordatorio1;
    private javax.swing.JComboBox<String> CategoriaTarea;
    private javax.swing.JTextField DescripcionTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
