package Vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Vista.Principal;
import Vista.GestionTareas;
import Vista.TareasCompletadas;
import Controlador.ControladorTareas; 
import java.awt.BorderLayout;
import java.time.LocalDate;
import javax.swing.JPanel;

/**
 *
 * @author pinzo
 */
public class ToDoList extends javax.swing.JFrame {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ToDoList.class.getName());

    private BorderLayout borderLayout = new BorderLayout();
    
    // 1. DECLARAMOS LOS PANELES COMO VARIABLES DE CLASE (Para no perderlos)
    private Principal pPrincipal;
    private GestionTareas pGestion;
    private TareasCompletadas pCompletadas;
    
    // 2. DECLARAMOS EL CONTROLADOR
    private ControladorTareas controlador;

 
public ToDoList() {
       initComponents();
        SetDate();
        
        // 1. CREAMOS LOS PANELES (Solo una vez)
        // IMPORTANTE: Le pasamos 'this' al Principal para que pueda llamarnos de vuelta
        pPrincipal = new Principal(this); 
        
        pGestion = new GestionTareas();
        pCompletadas = new TareasCompletadas();
        
        // 2. CONECTAMOS EL CONTROLADOR
        controlador = new ControladorTareas(pGestion, pCompletadas);
        
        // 3. Mostramos la pantalla de inicio
        Mostrarventanas(pPrincipal);
    }

    private void Mostrarventanas(JPanel p){
        Content.setLayout(borderLayout);
        p.setSize(830, 458);
        p.setLocation(0,0);
        
        Content.removeAll();
        Content.add(p, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Fondo = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        MenuPrincipal = new javax.swing.JButton();
        GestionTareas = new javax.swing.JButton();
        TareasCompletadas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Encabezado = new javax.swing.JPanel();
        Fecha = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        Slogan = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setBackground(new java.awt.Color(0, 102, 204));
        Menu.setPreferredSize(new java.awt.Dimension(270, 640));

        MenuPrincipal.setBackground(new java.awt.Color(0, 153, 255));
        MenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos img/house_3661264 (3).png"))); // NOI18N
        MenuPrincipal.setText("Principal");
        MenuPrincipal.setBorder(null);
        MenuPrincipal.setBorderPainted(false);
        MenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalActionPerformed(evt);
            }
        });

        GestionTareas.setBackground(new java.awt.Color(0, 153, 255));
        GestionTareas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GestionTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos img/portapapeles (1).png"))); // NOI18N
        GestionTareas.setText("Gestiona tus tareas");
        GestionTareas.setBorder(null);
        GestionTareas.setBorderPainted(false);
        GestionTareas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GestionTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionTareasActionPerformed(evt);
            }
        });

        TareasCompletadas.setBackground(new java.awt.Color(0, 153, 255));
        TareasCompletadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TareasCompletadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos img/correcto (1).png"))); // NOI18N
        TareasCompletadas.setText("Tareas Completadas");
        TareasCompletadas.setBorder(null);
        TareasCompletadas.setBorderPainted(false);
        TareasCompletadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TareasCompletadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TareasCompletadasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GestionTareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TareasCompletadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addGap(98, 98, 98)
                .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GestionTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TareasCompletadas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        Encabezado.setBackground(new java.awt.Color(102, 153, 255));
        Encabezado.setPreferredSize(new java.awt.Dimension(543, 150));

        Fecha.setBackground(new java.awt.Color(255, 255, 255));
        Fecha.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("Hoy es {dayname} {day} de {month} de {year}");

        Bienvenido.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        Bienvenido.setText("Bienvenido");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bienvenido)
                    .addComponent(Fecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Bienvenido)
                .addGap(6, 6, 6)
                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Slogan.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        Slogan.setForeground(new java.awt.Color(102, 102, 102));
        Slogan.setText("Organiza tu día, conquista tus metas. ");

        Content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(Slogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(539, 539, 539))
                    .addComponent(Encabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                    .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Slogan)
                .addGap(18, 18, 18)
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalActionPerformed
        // ERROR: Estás creando OTRO Principal, que estará vacío y sin conexión
        // Principal p1 = new Principal(); 
        
        // CORRECCIÓN: Tienes que usar la variable que ya creaste arriba
        Mostrarventanas(pPrincipal);;
    }//GEN-LAST:event_MenuPrincipalActionPerformed

    private void GestionTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionTareasActionPerformed
        Mostrarventanas(pGestion);
    }//GEN-LAST:event_GestionTareasActionPerformed

    private void TareasCompletadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TareasCompletadasActionPerformed
        Mostrarventanas(pCompletadas);
    }//GEN-LAST:event_TareasCompletadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ToDoList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Fecha;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton GestionTareas;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton MenuPrincipal;
    private javax.swing.JLabel Slogan;
    private javax.swing.JButton TareasCompletadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void SetDate() {
    LocalDate now = LocalDate.now();
    int Year = now.getYear();
    int dayOfMonth = now.getDayOfMonth();
    int month = now.getMonthValue();
    int dayOfWeek = now.getDayOfWeek().getValue(); 
    String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
    String[] dias = {"Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"}; 
    
    Fecha.setText("Hoy es " + dias[dayOfWeek - 1] + ", " + dayOfMonth + " de " + meses[month - 1] + " de " + Year);
    }

    public void irAGestionTareas() {
        // Llamamos a tu método privado que cambia el panel
        // Le pasamos "pGestion", que es la variable que TIENE el controlador conectado
        Mostrarventanas(pGestion);
    }

  
    
}
